### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by jcbaillie** [massalabs/station#1055] opened 2023-07-27 05:56 UTC
**The problem(s)**

The installer for version 0.3.0 does not work at all on Windows (tested on Windows 10, all updates done)

**To Reproduce**

Download https://github.com/massalabs/station/releases/download/v0.3.0/massastation_windows_amd64.exe
Launch in a cmd.exe terminal (fails also when in administrator mode)

**Expected behavior(s)**

The installer should start.

**Screenshots**

Logs:

```
C:\Users\User\Downloads>massastation_windows_amd64.exe                                                                  
2023/07/27 09:52:59 while initializing logger: initialize global logger: open log file: open C:\Users\User\Downloads\logs\massastation.log: The system cannot find the path specified.    
```   

**MassaStation version**
The version of MassaStation the bug is present in.

Version 0.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 
 **Any other useful info**

**Comment by thomas-senechal** [comment] 2023-07-27 09:14
Hi @jcbaillie !

It's because you downloaded the wrong file
For Windows, you are supposed to download the `.msi` file as explained in the [`INSTALLATION.md`](https://github.com/massalabs/station/blob/main/INSTALLATION.md#windows-installation)

**Comment by jcbaillie** [comment] 2023-07-27 10:15
OK, thanks (maybe we should remove the .exe then? it's the only file with "windows" in it, it seems to be the obvious choice for a download)

Now the installer crashes with:
<img width="389" alt="image" src="https://github.com/massalabs/station/assets/986939/2f55167d-8d17-4025-b9ef-9f2fa6290f93">

**Comment by thomas-senechal** [comment] 2023-07-27 10:31
> OK, thanks (maybe we should remove the .exe then? it's the only file with "windows" in it, it seems to be the obvious choice for a download)

Users will download MassaStation from the landing page once ready, so this shouldn't be an issue. But we will see if we can improve this 


> Now the installer crashes with:
> <img width="389" alt="image" src="https://github.com/massalabs/station/assets/986939/2f55167d-8d17-4025-b9ef-9f2fa6290f93">
> 

This error can be safely ignored
It just means that Acrylic (the local dns we install) has been already installed, probably with an older version of MassaStation. We are planning to fix this issue once we have some time for it, but for now, you can ignore it by pressing the "ok" button ! :)

**Comment by jcbaillie** [comment] 2023-07-27 11:40
Another possible explanation is that I have a VPN installed (but not active)? When I select "Open MassaStation" in the right click menu from the Massa Station icon, I get this error in Brave when accessing `station.massa` (also in Chrome):

```
station.massa’s DNS address could not be found. Diagnosing the problem.
DNS_PROBE_POSSIBLE
```

suggesting that perhaps indeed there is a problem with Acrylic?

**Comment by thomas-senechal** [comment] 2023-07-27 12:55
From the `C:\Program Files (x86)\MassaStation` directory, could you try to run `configure_acrylic.bat` ? 
If the issue still isn't fixed, could you also try to run `configure_network_interfaces.bat`

**Comment by jcbaillie** [comment] 2023-07-27 14:03
`configure_acrylic.bat` simply closes the cmd.exe shell (I couldn't see any output), and it did not fix the issue.

`configure_network_interfaces.bat` also closes the shell without fixing the issue, but something prints out very fast and I was able to capture it with a recording of the session:

```
Executing configure_network_interfaces.bat
Configuring Ethernet4...
The filename, directory name, or volume label syntax is incorrect.

The filename, directory name, or volume label syntax is incorrect.

Configuring vEthernet(WSL)...
The filename, directory name, or volume label syntax is incorrect.
```

This reminds me I forgot to tell you WSL is installed also, possibly messing with some network level stuff.

**Comment by thomas-senechal** [comment] 2023-07-27 14:54
Oh yes, for now, MassaStation isn't compatible with WSL. Acrylic requires port 53 to work properly, but it is already used by WSL.

We are tracking this problem here: https://github.com/massalabs/station/issues/466

**Comment by gregLibert** [comment] 2023-07-28 09:11
duplicate of #466

**Closed by gregLibert** 2023-07-28 09:11 UTC
Labels: issue:bug
