### ISSUE TITLE
Installation - MacOS: Enable the installation of a new massa station version even if I've got an old one installed

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1031] opened 2023-07-20 15:04 UTC
**Context**
As a user, if I forget that I have Massa Station installed on my computer and that I go and install a new / another version of massa station, I want to be able to install the new version and access the product.

Current behaviour: the installed failed
see attached logs
[Installer Log 20-Jul-2023.txt](https://github.com/massalabs/station/files/12111387/Installer.Log.20-Jul-2023.txt)

**How to**

- [ ] Update the installer to either
Option 1: simply display a message to say that massa station is already installed and so an update should be installed instead of re-installing the all application 
Option 2: make sure the installation is successful and enable users to open the new app installed

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**

Follow the user flow above

**Comment by Thykof** [comment] 2023-07-24 09:42
after reading the logs, the error comes from https://github.com/massalabs/station/blob/dcc5303819ea704601b9a414a2d585b48cf30cdd/installer/macos/scripts/postinstall#L71

but `mkdir` shouldn't throw an error with option `-p`

we can see in the logs that it fails `mkdir: /usr/local/share/massastation: File exists`

Here are the step I did to try to reproduce the error you encountered: 
- uninstall Massa Station
- install v0.2.0 with .pkg file
- install v0.3.0 with .pkg file
Everything went well.

I would need more details on how you fired this error.

**Comment by gregLibert** [comment] 2023-07-28 09:14
@Thykof if you (you, @thomas-senechal  + @longgamma-massa ) are not able to reproduce, as Solene won't answer on that for a significant time, close it instead of moving it to block.

**Comment by Thykof** [comment] 2023-07-28 09:20
I close then, feel free to re open if needed.

**Closed** 2023-07-28 10:01 UTC
Labels: P1
