### ISSUE TITLE
Installation windows - root CA is not reinstall after uninstall

### ISSUE THREAD

**Issue by gregLibert** [massalabs/station#766] opened 2023-06-15 10:02 UTC
**The problem(s)**
The Root Ac is not reinstall after undeinstall

**To Reproduce**
- Install massa station
- Uninstall it
- manually remove the mkcert AC
- reinstall massa station

=> mkcert AC is not here

if I execute manualy the batch script to install and generate a certificate, it works (mkcert is reinstall the mkcert AC)

**Expected behavior(s)**
Installation of massastation shall install the mkcert AC if it doesn't exist.

**Thyra version**
Last version

**Desktop (please complete the following information):**
Windows 11
 
 **Any other useful info**

**Comment by Thykof** [comment] 2023-06-29 12:38
I can't reproduce the issue.

When I remove directory C:\Users\Nathan\AppData\Local\mkcert and I run the installer it ask me:
![image](https://github.com/massalabs/station/assets/11590067/8810572e-2c29-47f5-addc-bf7c6f78c72b)

When I click Yes, Root CA are installed, so no problem.

If a click no, I have
![image](https://github.com/massalabs/station/assets/11590067/07e29e13-52a0-4636-b2fb-b06fa5a23c89)

and the installation failed

**Comment by Thykof** [comment] 2023-06-30 15:16
I close the issue as we were unable to reproduce the problem. However, please feel free to reopen the issue if needed.

**Comment by gregLibert** [comment] 2023-06-30 17:45
I'm reopening it tonight because last version of massaStation failed because of it. I checked the trust store and indeed the mkcert CA certificate was there. Running mkcert -install solve the problem.

The question is why mkcert wasn't properly executed ?
FIY, both cert and cert-key of the CA were present, simply the certificate was present in windows trust store.

**Comment by gregLibert** [comment] 2023-06-30 17:46
i will continue my investigation.

**Comment by Thykof** [comment] 2023-07-10 08:45
In https://github.com/massalabs/station/releases/tag/v0.2.5 the certificate is installed when Massa Station starts.

**Closed by Thykof** 2023-07-10 08:45 UTC
Labels: issue:bug, P1
