### ISSUE TITLE
Ubuntu: mkcert download failed during installation

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/station#823] opened 2023-06-21 08:14 UTC
**The problem(s)**

1) GUI wasn't working stuck at 20% for multiple minutes) + dpkg problem

![Screenshot from 2023-06-20 09-39-37](https://github.com/massalabs/station/assets/90157528/2b461144-8718-4ec7-b0e2-fb749f1d33fa)

2) Manual install was not working correctly: 
![Screenshot from 2023-06-20 10-07-53](https://github.com/massalabs/station/assets/90157528/7db0b960-0a6a-4f58-b870-c0b91c800525) 

3) fixing the manual install problem by downloading mkcert : 
`curl -sL "https://dl.filippo.io/mkcert/latest?for=linux/amd64" -o mkcert`

4)Installing the plugin manually using sudo apt install 
![Screenshot from 2023-06-20 14-46-07](https://github.com/massalabs/station/assets/90157528/550be84e-06ce-43dd-b056-7b5fbcb3bf70)

5)Unable to connect to url : 

https://station.massa/ after installation 

![Screenshot from 2023-06-20 14-47-48](https://github.com/massalabs/station/assets/90157528/3f84ef39-f9ce-46ed-98c2-e020f1d653e4)

**MassaStation version**
0.2.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 
 **Any other useful info**

**Comment by Thykof** [comment] 2023-06-22 06:30
I've experienced the same issue.

**Comment by SlnPons** [comment] 2023-06-26 07:52
@pivilartisant when you have time could you uninstall completely massa station using the step by step here https://github.com/massalabs/station/blob/main/INSTALLATION.md#uninstallation
and test it again with v0.2.3 please?

**Comment by pivilartisant** [comment] 2023-06-27 13:34
So from my testing the issue remains and the steps to install Massa Station correctly have not changed for me. The major difference is that Firefox now allows the connection and doesn't systematically block it !

**Comment by SlnPons** [comment] 2023-06-27 15:14
> So from my testing the issue remains and the steps to install Massa Station correctly have not changed for me. The major difference is that Firefox now allows the connection and doesn't systematically block it !

What do you mean by "it allows the connection"? 
--> which one? secure? or not secure?

**Comment by thomas-senechal** [comment] 2023-06-27 15:33
> @thomas-senechal is firefox working on windows, do you remember? Because I know it is not on Mac.

Just tried it on both Windows and MacOS:
- On MacOS, HTTPS works on Firefox 
- On Windows, HTTPS does not work on Firefox, but the issue is just that Firefox isn't supported by mkcert: https://github.com/FiloSottile/mkcert/issues/239

We should add a warning somewhere about this issue with Firefox on Windows and investigate the issue when we will have some time

**Comment by thomas-senechal** [comment] 2023-06-27 15:36
We tried to fix this issue on Windows a few months ago: 
- https://github.com/massalabs/station/issues/381
- https://github.com/massalabs/station/issues/406

Maybe we broke the fix, maybe it just didn't worked, I don't know

**Comment by SlnPons** [comment] 2023-06-27 16:09
We're talking about Linux here @thomas-senechal 😅
But I assume it's working on Linux too. So this issue is related to something else

**Comment by pivilartisant** [comment] 2023-06-28 08:34
> > So from my testing the issue remains and the steps to install Massa Station correctly have not changed for me. The major difference is that Firefox now allows the connection and doesn't systematically block it !
> 
> @pivilartisant What do you mean by "it allows the connection"? --> which one? secure? or not secure?

sorry for bad communication : firefox on mac allows this both http & https without any warning. Firefox in linux ubuntu 22.04 does not allow any http & https connection to the station.massa

**Comment by SlnPons** [comment] 2023-06-28 11:34
ok thanks @pivilartisant. 

@thomas-senechal I think you have ubuntu too. When you have time can you test this on your side and see if you can reproduce please? (ie: no access to http nor https = no access to massa station) 
Let me know, but don't bother to look at the issue. Someone else will do it :)

**Comment by thomas-senechal** [comment] 2023-06-28 11:53
> @thomas-senechal I think you have ubuntu too. When you have time can you test this on your side and see if you can reproduce please? 

@SlnPons , I just checked and everything is working flawlessly. HTTP and HTTPS were working on Firefox and Chome on my Ubuntu laptop.
Steps I followed:
- Uninstall Massa Station using `sudo apt remove massastation`
- Download Massa Station `.deb` from the latest release
- Install Massa Station with `sudo apt install ./massastation.deb` 
- Start Massa Station from the Applications menu

**Comment by SlnPons** [comment] 2023-06-28 13:24
Closing this issue as we can't reproduce. @pivilartisant if you have trouble installing Massa Station, ping me to follow the above procedure together :)

**Comment by Thykof** [comment] 2023-06-28 14:10
the first problem on the issue description is about FATAL: `mkcert download failed`. 

To solve this issue, @pivilartisant give us a workaround, that I was able to reproduce, thanks ;)

- `curl -sL "https://dl.filippo.io/mkcert/latest?for=linux/amd64" -o mkcert`
- `sudo apt install ./massastation_0.2.3_amd64.deb`

however the error persist with `sudo dpkg -i ./massastation_0.2.3_amd64.deb`

**Comment by Thykof** [comment] 2023-06-28 14:12
However @SlnPons @thomas-senechal I think we should try to fix the error `mkcert download failed`.

**Comment by Thykof** [comment] 2023-06-29 12:58
to solve the mkcert download failed, we can ping 1.1.1.1 with timeout of 15 sec, so it will wait for network manager to properly restart, and so the curl will succeed.

**Comment by Pierregvx** [comment] 2023-06-30 13:32
I got `/var/lib/dpkg/info/massastation.postinst: line 64: ifconfig: command not found` with the installer built

**Closed** 2023-07-03 08:15 UTC
Labels: issue:bug, P1
