### ISSUE TITLE
Add config and plugins directories options

### ISSUE THREAD

**Issue by thomas-senechal** [massalabs/station#279] opened 2022-11-21 14:09 UTC
I think it would be great to have a way to specify at launch, which directory to use for the configurations, the wallets, and the plugins. Like `--wallet-directory`, `--plugins-directory` and others. 

I don't think it's something that should be done in this PR since it's not 100% linked to this issue and it's not important, but might be great to add those options for users that might want to be able to find there files easily, especially on Windows and MacOS where `$HOME` isn't easily accessible through file explorers. 

_Originally posted by @thomas-senechal in https://github.com/massalabs/thyra/issues/251#issuecomment-1321778342_

**Comment by SlnPons** [comment] 2022-12-29 14:33
@peterjah I'm not sure to fully understand what this issue will change for plugins users. 
I feel like it's a nice to have, but could you give me your opinion please?

**Comment by SlnPons** [comment] 2023-01-27 08:47
@gregLibert could you give me your opinion on this issue please? I'm not sure to understand / evaluate correctly the value it will bring for us or our users.

**Comment by gregLibert** [comment] 2023-01-27 14:46
@SlnPons Interesting but not sure about the value neither. A good first issue not for now ?

**Comment by SlnPons** [comment] 2023-03-06 13:47
As discussed @thomas-senechal, this issue is not a priority. However this subject needs to be tackled by the mainnet date. 

Note: for the mainnet, thyra's flags and variables should be documented and accessible for dev-users.

**Comment by gregLibert** [comment] 2023-12-27 08:25
For the plugin directory, this issue should be addressed during the plugin rework. @SlnPons, please let me know if you think my cleanup was excessive.

For the rest, duplicate of #1079

**Closed by gregLibert** 2023-12-27 08:25 UTC
Labels: good first issue, question, improvement_plugin_manager
