### ISSUE TITLE
Installation on Windows 11: can't open https

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#758] opened 2023-06-14 13:51 UTC
**The problem(s)**
I can't open https links after having installed MassaStation with the install script.

**To Reproduce**

1. Use the windows installer in this release: https://github.com/massalabs/thyra/releases/tag/v0.2.0
2. Installation is successful 
3. Open MassaStation using the icon tray: it opens http://station.massa/home/
4. try to access https://station.massa/home/ or https://station.massa/store/ --> it fails

**Expected behavior(s)**
1. Icon tray should automatically open HTTPS
2. If user uses https link, they should be able to access them

**Screenshots**
<img width="1097" alt="image" src="https://github.com/massalabs/thyra/assets/109611779/8035185b-ba27-4410-a31e-427961b6af30">

<img width="1096" alt="image" src="https://github.com/massalabs/thyra/assets/109611779/93b25a16-8c28-46cf-9b6f-3ef2db95aec3">

**Thyra version**
v0.2.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome

**Comment by gregLibert** [comment] 2023-06-14 14:59
![MassaStation-AC](https://github.com/massalabs/thyra/assets/16623956/94bc23da-861d-425c-bedb-4903a08b1a6f)

**Comment by gregLibert** [comment] 2023-06-14 15:00
![MassaStation-chrome](https://github.com/massalabs/thyra/assets/16623956/4d29af72-d2ca-4028-a609-a6574b11ec6f)

**Comment by SlnPons** [comment] 2023-06-14 17:45
@thomas-senechal do you know how to solve this? 
If so could you estimate please? 
If no, then let's see what's the priority based on your other tasks so we avoid context switch ;)

**Comment by gregLibert** [comment] 2023-06-16 07:42
After doing some tests on my side, simply restarting the browser (not the computer) is sufficient to solve this problem. If this is confirm, we should add a message to invite the user to do so.

**Comment by SlnPons** [comment] 2023-06-19 07:50
Maria tested on her side, it wasn't working. 
--> The conclusion here: we need to assist the user to make it works because it's not straightforward for non-tech to do it correctly. 
(I believe the solution you shared with us Greg is working, just it's not easy for non-tech to do it right)

We must add a step to close and re-open all browser windows on Windows.

**Comment by gregLibert** [comment] 2023-06-19 08:12
> (I believe the solution you shared with us Greg is working, just it's not easy for non-tech to do it right)

This need to be confirmed...

**Comment by SlnPons** [comment] 2023-06-26 07:50
I can confirm that the solution suggested in comment by Greg is not working. Multiple windows 11 users reported me that they were unable to open https even after closing their browser completely. If we need to restart the computer then we should make sure it is done "automatically" at the end of the install process after asking the user to do so.

**Comment by Thykof** [comment] 2023-06-29 09:27
I tested on windows 11 with firefox, restarting firefox didn't work, restart the computer neither.

When I manually install mkcert certificates:

```
C:\Users\Nathan>mkcert.exe --install
The local CA is already installed in the system trust store! 👍
Note: Firefox support is not available on your platform. ℹ️
```

**Comment by Thykof** [comment] 2023-06-29 09:31
https worked well on Microsoft Edge. I uninstalled and installed again, without closing Microsoft Edge and it also work.

**Comment by Thykof** [comment] 2023-06-29 09:40
same for Chrome.

So I guess wa can close this issue and reopen this one https://github.com/massalabs/station/issues/381#issuecomment-1372491984

**Comment by Thykof** [comment] 2023-06-30 15:18
The original issue is about Windows 11 with Google Chrome. @SlnPons do you still experience the issue? Do you know if users that reported the issue used Firefox?

**Comment by SlnPons** [comment] 2023-07-03 07:00
Let's catch up about this @Thykof. Yes, I've got users experiencing this + Brian & John are on Windows 11 and Chrome so let's avoid another disappointement here 😅
Lucas & Maria are on windows 11. Maria experienced this issue.

**Comment by thomas-senechal** [comment] 2023-07-03 07:33
I just tried to install Station on a fresh Windows 11 install, and I have the issue.

**Comment by gregLibert** [comment] 2023-07-03 07:42
> I just tried to install Station on a fresh Windows 11 install, and I have the issue.

Can you confirm that mkcert is not part of the known CA ?

**Comment by thomas-senechal** [comment] 2023-07-03 08:05
> Can you confirm that mkcert is not part of the known CA ? (using the GUI, not certutil CLI)

I confirm. I couldn't find it in the list of known CA.

**Comment by gregLibert** [comment] 2023-07-03 08:15
> I confirm. I couldn't find it in the list of known CA.

So I think we can link this issue with #766

**Comment by thomas-senechal** [comment] 2023-07-03 09:06
Since running the script manually fixes the issue, I think changing `Impersonate` to `yes` in the `GenerateCertificate` CustomAction should fix the issue: https://github.com/massalabs/station/blob/b9eb48d4d22357ed887a1835ce24ce3cbdb07644/installer/windows/build_installer.py#L316

But I'm unsure that this will work for all users on the computer since it will inpersonate the user installing MassaStation.

**Comment by gregLibert** [comment] 2023-07-03 14:06
> Since running the script manually fixes the issue, I think changing `Impersonate` to `yes` in the `GenerateCertificate` CustomAction should fix the issue:
> 
> https://github.com/massalabs/station/blob/b9eb48d4d22357ed887a1835ce24ce3cbdb07644/installer/windows/build_installer.py#L316
> 
> But I'm unsure that this will work for all users on the computer since it will inpersonate the user installing MassaStation.

My tests on windows: when we execute it using "run as admin", certificate is correctly added to user root CA. But this is maybe a side effect of running a command as admin in the context of a user. Who knows...

I think that the previous suggestion should be tested @Thykof !

**Comment by gregLibert** [comment] 2023-07-03 17:25
fix attemp failed, see https://github.com/massalabs/station/pull/943#issuecomment-1618915343

**Comment by Thykof** [comment] 2023-07-04 07:06
I reopen and revert the the fix

**Comment by Thykof** [comment] 2023-07-07 12:56
**Windows clean up procedures**

Full clean of mkcert:
- Open the search menu on windows (near the Windows icon)
- Type "certificates"
- Open "User certificates" (or somthing similar)
- On the left panel, click on "Trusted Root Certificate Authority" (or something similar)
- Then, click on "Certificates"
- Then, find the line starting with "mkcert"
- Right click this line, and "delete" it
- Close the User Certificates window
- Open a file explorer
- In the text box of the top bar, write "%APPDATA%"
- You might endup in the "Roaming" directory, go to "AppData" by clicking on it in the text box of the top bar
- Go to "Local"
- Find "mkcert" directory
- Delete the "mkcert" directory

uninstall on windows:
- Settings
- Apps
- Installed Apps
- search Massa
- chose uninstall

Then I downloaded the .msi file from the artifact of the main branch (just before 0.2.5) and installation of Massa Station passe without issue. I can use Massa Station with https on Chrome and Microsoft Edge, but not on Firefox.

**Comment by Thykof** [comment] 2023-07-07 13:20
So I am closing this issue.

For windows on Firefox, this issue follows up: https://github.com/massalabs/station/issues/961

**Closed by Thykof** 2023-07-07 13:20 UTC
Labels: issue:bug, P1

**Comment by SlnPons** [comment] 2023-07-07 15:37
This has been solved for chromium. Pending solution for firefox <> windows, see: https://github.com/massalabs/station/issues/961
