### ISSUE TITLE
Search page - Website upload display my wallet account but don't select it

### ISSUE THREAD

**Issue by SlnPons** [massalabs/station#1038] opened 2023-07-21 09:45 UTC
**The problem(s)**
When I create a wallet using massa wallet for the very first time, and that I go on the search page side panel, I can see that my account is appearing in the dropdown. 
When I complete the rest of the info and that I click on upload, the upload failed. 

--> the upload failed because even if the account name is displayed, it is not selected and so the upload can't be done as no account is linked.

**To Reproduce**

1. Delete all your massa wallet accounts 
2. GO on the search page and verify that you have the create account button display on the side panel
3. click on the create account button 
4. Create your account (with MASSA in it)
5. GO back to station
6. Without doing anything, you should see the created account name displayed in the dropdown
7. Complete other info needed to upload your website
8. Click on upload 
9. the upload failed 

10. Re-do the same process, but at step 6. instead of doing nothing, click on the dropdown and select the one and only account you can see.
11. This time it will work

**Expected behavior(s)**

If the account is displayed in the dropdown then it suggests that it is selection / active and so it should work.
**Screenshots**

**MassaStation version**
v0.3.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome

**Comment by longgamma-massa** [comment] 2023-08-14 14:22
I experience the same error and flow as described in Solene's description.

**Comment by longgamma-massa** [comment] 2023-08-14 14:23
@Thykof someone should take a look into this

**Comment by Thykof** [comment] 2023-08-16 09:57
@thomas-senechal can have a look later today

**Comment by thomas-senechal** [comment] 2023-08-17 13:35
> Q/A: I experienced the same error while testing the flow as described in the issue description. Needs KO

Hi @longgamma-massa , 

I tried to reproduce the issue on `main` (precise commit [1ce8f96](https://github.com/massalabs/station/tree/1ce8f964407db6009acfa6bae32e3b6a9c22de3b)) but couldn't reproduce the issue

Could you try to reproduce it on your side ? 
If it happens, could you tell me if after pressing the "Upload" button, the password window appeared ?

Thanks a lot

**Comment by longgamma-massa** [comment] 2023-08-21 15:46
couldn't reproduce again. I will close the issue.

**Closed** 2023-08-21 15:49 UTC
Labels: issue:bug, P2, Frontend
