### ISSUE TITLE
Large file upload error " Key not found "

### ISSUE THREAD

**Issue by AltayDev** [massalabs/station#1169] opened 2023-09-15 08:39 UTC
**The problem(s)**
It takes 29 minutes to upload zip files larger than 14 MB and then 
![image](https://github.com/massalabs/station/assets/145108492/ce47dfb2-576c-4659-9c11-f3a3f2e87a32)
error.

**To Reproduce**
My Steps
- I converted my build to .zip.
- If MassaStation is open, I completely exited the icon and restarted it with the parameter <code>$env:UPLOAD_MAX_SIZE = "1000000000".</code>
- I entered this code to upload my file: 
 <code>curl -X PUT -F "url=name" -F "nickname=Altay" -F "description=website des" -F "zipfile=@build.zip" http://station.massa/websiteUploader/prepare</code>
- gave the above error after an average of 20 minutes

**MassaStation version**
massastation_0.3.4_amd64.msi

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Thykof** [comment] 2023-09-29 12:48
The problem is due to the fact that the cache item has a lifetime of 20 minutes. So if user upload a large file, the loading time can be higher than 20 minutes and the correlation ID of the batch request is removed from the cache. 

We will improve how we handle batch request.

**Comment by Thykof** [comment] 2023-10-26 00:12
thanks to https://github.com/massalabs/station-massa-wallet/pull/778 the developer will be able to customize the cache lifetime by setting this environment variable: BATCH_EXPIRATION_TIME

The value must follow input requirement of https://pkg.go.dev/time#ParseDuration, for example "50m" for 50 minutes

**Comment by gregLibert** [comment] 2023-12-27 08:38
@AltayDev is this still blocking you? if not, @SlnPons I suggest to improve that in the woc rework.

**Comment by SlnPons** [comment] 2023-12-29 16:35
As we got no answer, I'll close this issue and I can confirm you that the upload speed is part of the improvements identified for this product :)

**Closed by SlnPons** 2023-12-29 16:35 UTC
Labels: issue:bug
